name: LaTeX PDF Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clean Unicode (U+202F)
        run: |
          find src -name '*.tex' -print0 | xargs -0 sed -i 's/â€¯/ /g'

      - name: Install TeX + Make
        run: |
          sudo apt-get update
          sudo apt-get install -y \
           texlive-latex-recommended \
           texlive-latex-extra \
           texlive-fonts-recommended \
           texlive-publishers \
           texlive-bibtex-extra \
           latexmk \
           lmodern
      - name: Build PDF (ignore latexmk errors)
        run: make

      - name: Debug Build Files
        run: |
           ls -R build
           cat build/aw4null-overview.log || true


      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/aw4null-overview.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
